name: "install ci"
description: "ci install and git ssh setup"

runs:
  using: "composite"
  steps:

    - name: cache virtualenv
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      with:
        path: |
          .venv
        key: ${{ runner.os }}-poetry-v2-${{ hashFiles('./poetry.lock') }}

    - name: install dependencies
      shell: bash
      run: make install-ci
