name: Dependabot
version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      open-pull-requests-limit: 2
      schedule:
          interval: "daily"
          time: "03:00"
      commit-message:
          prefix: "github actions "
          include: scope

    - package-ecosystem: "pip"
      directory: "/"
      open-pull-requests-limit: 2

      schedule:
          interval: "daily"
          time: "11:38"
      commit-message:
          prefix: "py dev "
          include: scope
