name: "sonar scan"
description: "run sonar scan"
inputs:
  github-token:
    required: true
    description: "github token secret"
  sonar-token:
    required: true
    description: "sonar token secret"

runs:
  using: "composite"
  steps:
    - name: code coverage
      shell: bash
      run: make coverage-ci

    - name: code coverage report
      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      uses: orgoro/coverage@ca0c362dc1a4f100447309405e6dfea47e251495 # v3.3.1
      with:
        coverageFile: reports/coverage.xml
        token: ${{ inputs.github-token }}
        thresholdAll: 0.65 # TODO increase to 0.85 as coverage improves

    - name: prepare sonar reports
      if: success() || failure()
      shell: bash
      run: |
        cat sonar-project.properties
        scripts/sonar_tests.py

    - name: sonar scan
      if: success() || failure()
      uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
