name: create-release
on:
  push:
    tags:
      - "v*"

jobs:

  coverage:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/terraform-aws-mesh-client' && !contains(github.event.head_commit.message, 'tag release version:')
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: common build setup
        uses: ./.github/actions/build-common

      - name: get tag
        run: |
          VERSION="${GITHUB_REF#refs/*/}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
