name: "Secret Scanner"

on:
  push:
  pull_request:
    branches:
      - develop
  schedule:
    - cron: "0 8 * * 1,2,3,4,5"

jobs:
  trufflehog:
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--exclude_paths exclude-patterns.txt"
